In [1]:
import numpy as np

In [2]:
#提供数值计算的基础

In [3]:
myarr=np.arange(100000)
mylist=list(range(100000))
mylist
myarr

array([    0,     1,     2, ..., 99997, 99998, 99999])

In [4]:
%time for _ in range(10):myarr1=myarr*2   

CPU times: total: 0 ns
Wall time: 0 ns


In [5]:
%time for _ in range(10):mylist1=[x*2 for x in mylist]

CPU times: total: 46.9 ms
Wall time: 36.1 ms


In [6]:
#随机生成2行3列的数组
data=np.random.randn(2,3)
data

array([[ 0.45185696, -1.61464597,  0.92228583],
       [ 0.95614183,  0.08602926,  0.73759677]])

In [7]:
data+data

array([[ 0.90371391, -3.22929194,  1.84457166],
       [ 1.91228366,  0.17205851,  1.47519354]])

In [8]:
data*data

array([[0.20417471, 2.60708162, 0.85061115],
       [0.9142072 , 0.00740103, 0.54404899]])

In [9]:
data.T#转置

array([[ 0.45185696,  0.95614183],
       [-1.61464597,  0.08602926],
       [ 0.92228583,  0.73759677]])

In [10]:
#创建array数组
data1=[1,2,3,4,5,6]
data1

[1, 2, 3, 4, 5, 6]

In [11]:
arr1=np.array(data1)
arr1

array([1, 2, 3, 4, 5, 6])

In [12]:
data2=[[1,2,3,4,5],[6,7,8,9,0]]#data2是列表，numpy数组是arr2，它的两个维度shape是从data2中引入
arr2=np.array(data2)
arr2

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [13]:
arr2.ndim


2

In [14]:
arr2.shape#二维数组

(2, 5)

In [15]:
arr1.dtype

dtype('int32')

In [16]:
arr1=np.array([1,2,3],dtype=np.float64)
arr1.dtype


dtype('float64')

In [17]:
num=np.array(['1.15','-9.5','42'],dtype=np.string_)
num.astype(float)

array([ 1.15, -9.5 , 42.  ])

In [18]:
arr3=np.array([[0,4,5],[1,3,7]])
arr4=np.array([[1,2,6],[8,2,4]])
arr3>arr4#逐个比较大小，--广播

array([[False,  True, False],
       [False,  True,  True]])

In [19]:
arr1=np.arange(10)
arr1[2]
arr1[2:6]=3#2-5换成3
arr1

array([0, 1, 3, 3, 3, 3, 6, 7, 8, 9])

In [20]:
arr_slice=arr1[2:6]
arr_slice

array([3, 3, 3, 3])

In [21]:
arr_slice[1]=1234
arr1#arr1也会被改变

array([   0,    1,    3, 1234,    3,    3,    6,    7,    8,    9])

In [22]:
arr_slice[:]=6
arr1

array([0, 1, 6, 6, 6, 6, 6, 7, 8, 9])

In [23]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2
arr2[2][1]

8

In [24]:
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3
arr3.shape#三维数组
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [25]:
arr2d=[[1,2,3],[4,5,6],[7,8,9]]
arr2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [26]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr2d[:2,1:]#o-1行，1-所有列

array([[2, 3],
       [5, 6]])

In [28]:
arr2d[:2,1:]=0
arr2d


array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [29]:
#布尔索引-------------------------------------------------------
names=np.array((['Bob','Joe','Tim','Tom','Bob','Hel','Deo']))
data3=np.random.randn(7,4)

In [30]:
names=='Bob'

array([ True, False, False, False,  True, False, False])

In [31]:
data3

array([[-1.4020602 ,  0.81021443, -1.20643558, -0.40555405],
       [-1.57373126, -0.89977098,  0.96193657, -0.65870682],
       [ 0.24461592, -1.57397885, -1.34794936,  0.81706277],
       [ 0.68065513, -0.10040268, -0.84453855,  0.62923047],
       [-0.71413529, -1.13736407, -0.39238959, -1.29383113],
       [-1.48146703,  1.32746567, -1.11176094, -1.11651206],
       [-0.70409166, -0.1030958 , -0.80967247,  0.24983356]])

In [32]:
data3[names=='Bob',2:]#0行2列至后面所有列

array([[-1.20643558, -0.40555405],
       [-0.39238959, -1.29383113]])

In [33]:
data3[names=='Bob',3]

array([-0.40555405, -1.29383113])

In [34]:
cond=names=='Bob'
data3[~cond]#~取反的意思

array([[-1.57373126, -0.89977098,  0.96193657, -0.65870682],
       [ 0.24461592, -1.57397885, -1.34794936,  0.81706277],
       [ 0.68065513, -0.10040268, -0.84453855,  0.62923047],
       [-1.48146703,  1.32746567, -1.11176094, -1.11651206],
       [-0.70409166, -0.1030958 , -0.80967247,  0.24983356]])

In [35]:
1 is '1'

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\pc\AppData\Local\Temp\ipykernel_5456\3178425479.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  1 is '1'


False

In [36]:
2 is (1+1)

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\pc\AppData\Local\Temp\ipykernel_5456\3130079090.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  2 is (1+1)


True

In [37]:
mask=(names=='Bob')|(names=='Tim')
data3[mask]

array([[-1.4020602 ,  0.81021443, -1.20643558, -0.40555405],
       [ 0.24461592, -1.57397885, -1.34794936,  0.81706277],
       [-0.71413529, -1.13736407, -0.39238959, -1.29383113]])

In [38]:
data3[names=='Tim']=7
data3

array([[-1.4020602 ,  0.81021443, -1.20643558, -0.40555405],
       [-1.57373126, -0.89977098,  0.96193657, -0.65870682],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.68065513, -0.10040268, -0.84453855,  0.62923047],
       [-0.71413529, -1.13736407, -0.39238959, -1.29383113],
       [-1.48146703,  1.32746567, -1.11176094, -1.11651206],
       [-0.70409166, -0.1030958 , -0.80967247,  0.24983356]])

In [39]:
#矩阵内积---点乘对应元素点乘--------------------
arr=np.random.randn(6,3)
arr

array([[-2.71538611, -0.19063792, -0.09566119],
       [-0.73859654,  1.45165331,  0.37448997],
       [ 0.61334215,  0.85166183, -0.03852306],
       [-0.03139303,  0.12346852, -0.09688785],
       [-0.87013521,  0.34749074,  0.39443968],
       [ 0.4073128 , -0.567182  ,  0.67767825]])

In [40]:
np.dot(arr.T,arr)

array([[ 9.21905968, -0.56943091, -0.10461498],
       [-0.56943091,  3.32665775,  0.26979227],
       [-0.10461498,  0.26979227,  0.77509555]])