In [27]:
import numpy as np

In [30]:
np.random.random(6)

array([0.32076136, 0.99749135, 0.77489596, 0.05672838, 0.96819047,
       0.53509105])

In [31]:
np.zeros(2)

array([0., 0.])

In [33]:
np.zeros((2,3),dtype='int32')

array([[0, 0, 0],
       [0, 0, 0]])

In [34]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
np.full((2,4),fill_value=2)

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [98]:
arr2=[[1,2,3]]
arr3=np.squeeze(arr2)
arr3

array([1, 2, 3])

In [37]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
arr=np.array([1,1,1,2,3,7,0])
np.min(arr)

0

In [42]:
np.mean(arr)#平均数


2.75

In [44]:
np.average(arr)

2.75

In [51]:
np.median(arr)

1.0

In [57]:
arr1=[-1,-4,1,0,2,0]
np.count_nonzero(arr1)

4

In [58]:
np.sort(arr1)

array([-4, -1,  0,  0,  1,  2])

In [63]:
np.abs(arr1)

array([1, 4, 1, 0, 2, 0])

In [72]:
arr=np.array([1,.222,3.444,4.555])
np.round(arr,decimals=0)#四舍五入，0表示保留0为小数

array([1., 0., 3., 5.])

In [74]:
np.round(arr,decimals=1)

array([1. , 0.2, 3.4, 4.6])

In [79]:
arr3=np.array([1,3,5,7,2])
arr3[np.where(arr3>3)]

array([5, 7])

In [81]:
#给指定的值替换给指定元素----------------------------------

In [92]:
np.put(arr3,2,4)#替换单个直接写数字,替换arr3中的2位置值为4
arr3

array([1, 9, 4, 7, 2])

In [ ]:
np.put(arr3,[1,2],[9,8])#替换多个用列表
arr3